### ISSUE TITLE
Can not find documentation.

### ISSUE THREAD

**Issue by iitsuraj** [virtualvivek/react-windows-ui#8]
I am looking to use it in my upcoming CRM projects. But I can't find the documentation for it.

**Comment by virtualvivek** [comment]
Hi @iitsuraj ,

I am still working for the documentation and will release soon for the upcoming
`react-windows-ui -v4.0`

**Comment by virtualvivek** [comment]
Hi @iitsuraj ,

**react-windows-ui -v4.0.0** has been released.
The Documentation as per -v4.x Stable has been updated.
[Visit Documentation](https://virtualvivek.github.io/react-windows-ui/)
For Realease details and Changelogs:
[Visit Release](https://github.com/virtualvivek/react-windows-ui/releases/tag/v4.0.0)

If you find anything not valid or documentation is still not clear please comment with appropriate issues,
Otherwise give a confirmation for your issue resolved.
